apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-pod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx:alpine
